Add Android Plurals support
JcMinarro/Philology pull request #9
Opened 2019-07-03 15:53 UTC by pr0t3us

Since the [PluralRules](https://developer.android.com/reference/android/icu/text/PluralRules) API is available only from Android 7.0 (API level 24) added dependency to [com.ibm.icu:icu4j](https://github.com/unicode-org/icu) library. More about pre-nougat recommandation: [developer.android.com](https://developer.android.com/guide/topics/resources/internationalization#prenougat).

Implemented resources methods:`getQuantityText(id: Int, quantity: Int)`, `getQuantityString(id: Int, quantity: Int)` and `getQuantityString(id: Int, quantity: Int, vararg formatArgs: Any?)` to check for `id` and `keyword quantity` in repository. Check the sample app for more info regarding implementation details.

2019-07-15 09:28 UTC, JcMinarro requested changes
Hello @pr0t3us 
Thanks for your PR, that feature is really useful.
I have left some comments, could you review them?
On the other hand, I have seen you added tests for the new feature and seem to work fine, but it was only tested for "Quantity==1", Could we add new tests for the rest of plurals values?

2019-07-16 10:07 UTC, pr0t3us commented
@JcMinarro Glad you've liked this feature. I've addressed your questions in the pushed commits. Just let me know if this works or any changes needed.

2019-07-16 11:10 UTC, JcMinarro commented
It looks fine!!!!
Thank you.
Only one last update, because it is a "breaking change", we need to update the examples on the README.
Could you do that update?

2019-07-16 13:09 UTC, pr0t3us commented
@JcMinarro Sure, I've updated the `Readme.md` with basic usage of the plural resource.

2019-07-18 16:00 UTC, JcMinarro approved these changes

2019-07-18 16:02 UTC, merged